version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=sqlite:///data/db.sqlite3
    restart: unless-stopped
